#!/usr/bin/env bash
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]
print_domain_record () {
    record_and_ip=$(dig "$2"."$1" | awk '/^[^;]/ && /IN/ && /A[[:space:]]/ {print $4, $5}')
    
    # If no A record found, check for CNAME
    if [ -z "$record_and_ip" ]; then
        record_and_ip=$(dig "$2"."$1" | awk '/^[^;]/ && /IN/ && /CNAME/ {print $4, $5}')
    fi
    
    echo "$2" $record_and_ip | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 2 ]; then
    print_domain_record "$1" "$2"
else
    for sub in "www" "lb-01" "web-01" "web-02"; do
        print_domain_record "$1" "$sub"
    done
fi
